from . import patient
from . import doctor
from . import department
from . import week_day
from . import ward
from . import discharge_summary
from . import vitals
from . import lab
from . import radiology
from . import appointment
from . import visit
from . import prescription
from . import staff
from . import product
from . import account_move
from . import tag
